

export const fluxBlockchain= {
    id: "zelcash",
    libid: "zelcash",
    name: "Flux",
    symbol: "FLUX",
    decimals: 8,
    node: "https://explorer.runonflux.io",
    api: "https://api.runonflux.io",
    slip: 19167,
    scriptType: "p2pkh",
    messagePrefix: "\x18Zelcash Signed Message:\n",
    pubKeyHash: "1cb8", // 0x1cb8 = 7368
    scriptHash: "1cbd", // 0x1cbd = 7357
    wif: "80",
    logo: "https://assets.coingecko.com/coins/images/5163/large/FLUX.png",
    bip32: {
      public: 0x0488b21e,
      private: 0x0488ade4,
    },
    txVersion: 4,
    txGroupID: 0,
    backend: "insight",
    bech32: "",
    dustLimit: 546,
    minFeePerByte: 10,
    feePerByte: 10,
    maxMessage: 0,
    maxTxSize: 100000,
    rbf: false,
    cashaddr: "",
    txExpiryHeight: 0,
    hashType: 1,
    chainType: "UTXO",
    accountSalt: "",
    factorySalt: "",
    factoryAddress: "",
    entrypointAddress: "",
    baseFee: 0,
    priorityFee: 0,
    gasLimit: 0,
    tokens: [],
    onramperNetwork: "zelcash",
    chainId: undefined,
  }

  
export const bitcoinBlockchain = {
    id: "bitcoin",
    libid: "bitcoin",
    name: "Bitcoin",
    symbol: "BTC",
    decimals: 8,
    node: "https://btc-node.example.com",
    api: "https://btc-api.example.com",
    slip: 0,
    scriptType: "p2pkh",
    messagePrefix: "\x18Bitcoin Signed Message:\n",
    pubKeyHash: "00",
    scriptHash: "05",
    wif: "80",
    logo: "https://assets.coingecko.com/coins/images/1/large/bitcoin.png",
    bip32: {
      public: 0x0488b21e,
      private: 0x0488ade4,
    },
    txVersion: 1,
    txGroupID: 0,
    backend: "insight",
    bech32: "bc",
    dustLimit: 546,
    minFeePerByte: 1,
    feePerByte: 1,
    maxMessage: 0,
    maxTxSize: 100000,
    rbf: true,
    cashaddr: "",
    txExpiryHeight: 0,
    hashType: 1,
    chainType: "UTXO",
    accountSalt: "",
    factorySalt: "",
    factoryAddress: "",
    entrypointAddress: "",
    baseFee: 0,
    priorityFee: 0,
    gasLimit: 0,
    tokens: [],
    onramperNetwork: "bitcoin",
    chainId: undefined,
  }
  